xuperchain/contract-sdk-cpp

example/features.cc
Add more features example.  you can use it 
1. to learn how to use cpp contract features
2. for unit test of contract-sdk-cpp
3. for integration testing or unit test for bridge
=> Add more features example

example/features.cc
=> modify put method in feature.cc

.github/workflows/ci.yml, Makefile, test/crypto.test.js, test/features.test.js, test/game_assets.test.js, test/xuper_relay.test.js
=> add  ci pipeline

example/features.cc
=> example: allow specify amount and to address in  transfer method of features contract

test/features.test.js
=> example: update unit test for features contract

example/features.cc
=> example: allow specify amount and to address in transfer method of features contract

example/features.cc
=> example: add args check for features contract

.github/workflows/ci.yml, example/features.cc, src/xchain/context_impl.cc, src/xchain/context_impl.h, src/xchain/contract.pb.cc, src/xchain/contract.pb.h, src/xchain/xchain.h, test/features.test.js
=> context: add caller support in contract call

example/source_trace.cc
=> bugfix: fix value type error in contract example source_trace 

example/luck_draw.cc
=> bugfix:global variable initialize failed in example/luck_draw, which cause deploy failed

example/luck_draw.cc
=> [backport] bugfix:global variable initialize failed in example/luck_draw,which cause deploy failed (#23)

example/short_content.cc, src/xchain/basic_iterator.cc
=> bugfix:global variable initialize failed in example/short_content.cc

example/short_content.cc
=> [backport] bugfix:global variable initialize failed in example/short_content.cc

example/short_content.cc
=> [backport] bugfix:global variable initialize failed in example/short_content.cc(#26)

example/luck_draw.cc
=> bugfix: global variable initializing failed in luck_draw.cc

example/luck_draw.cc
=> [backport]bugfix: global variable initializing failed in luck_draw.cc (#29)

scripts/emcc.Dockerfile
=> bugfix: xrc01 build failed

example/award_manage.cc, example/erc20.cc, example/group_chain.cc, example/hash_deposit.cc, example/move.cc, reserved/unified_check.cc, src/xchain/table/table.h, src/xchain/xchain.h
=> remove all global string  objects

example/award_manage.cc, example/erc20.cc, example/group_chain.cc, example/hash_deposit.cc, example/move.cc, reserved/unified_check.cc, src/xchain/table/table.h, src/xchain/xchain.h
=> [backport] remove all global string objects (#33)

build.sh, example/group_chain.cc, example/hash_deposit.cc, src/xchain/context_impl.cc, src/xchain/xchain.h
=> exit script if build failed

build.sh, example/group_chain.cc, example/hash_deposit.cc, src/xchain/context_impl.cc, src/xchain/xchain.h
=> [backport]exit script if build failed (#36)

example/features.cc, test/features.test.js
=> features: add example of undefined behavior

build.sh
=> small fix of build script
